### ISSUE TITLE
Link to Lesson 6 broken

### ISSUE THREAD

**Issue by Flo082002** [MonsterDeveloper/java-telegram-bot-tutorial#12]
Hello.
You have created very good tutorials.
Unfortunately the Link to Chapter 6 is broken.
https://monsterdeveloper.gitbooks.io/writing-telegram-bots-on-java/content/
https://monsterdeveloper.gitbook.io/java-telegram-bot-tutorial/

**Comment by tehcmanmax** [comment]
Looks as he completely removed this chapter from Github

**Comment by MonsterDeveloper** [comment]
> Looks as he completely removed this chapter from Github

Nope, it's still there... Strange...

**Comment by MonsterDeveloper** [comment]
Seems fixed now!
