### ISSUE TITLE
Request to incorporate into library docs

### ISSUE THREAD

**Issue by rubenlagus** [MonsterDeveloper/java-telegram-bot-tutorial#16]
@MonsterDeveloper it has been a long time since this work was done and I'd like to incorporate it into the Docs I'm building for the library, would you mind if I copy the work into the repository: https://github.com/rubenlagus/TelegramBotsDocumentation and update it to the latest versions of the library (obviously, would make a reference to the original creator)?

**Comment by MonsterDeveloper** [comment]
Hi @rubenlagus! Absolutely not, it's my pleasure. Feel free to use my texts as you like, just keep the reference.

**Comment by rubenlagus** [comment]
Thanks, I've copied for now [here](https://rubenlagus.github.io/TelegramBotsDocumentation/java-telegram-bot-tutorial.html) and will start updating it.
