### ISSUE TITLE
Problem executing execute(msg) on sendPhoto

### ISSUE THREAD

**Issue by kamaubrian** [MonsterDeveloper/java-telegram-bot-tutorial#3]
Error:(65, 20) java: method execute in class org.telegram.telegrambots.bots.AbsSender cannot be applied to given types;
  required: Method
  found: org.telegram.telegrambots.api.methods.send.SendPhoto
  reason: inferred type does not conform to upper bound(s)
    inferred: org.telegram.telegrambots.api.methods.send.SendPhoto
    upper bound(s): org.telegram.telegrambots.api.methods.BotApiMethod<T>

**Comment by MonsterDeveloper** [comment]
Hey, try the code for sources in Lesson2/src.

**Comment by MonsterDeveloper** [comment]
Hi, fixed code in sources.

**Comment by kamaubrian** [comment]
Thank You
