### ISSUE TITLE
Execute doesn't compile

### ISSUE THREAD

**Issue by maxkwaaste** [MonsterDeveloper/java-telegram-bot-tutorial#4]
Hi,

I've copy pasted the code into IntelliJ, and the only error is that execute(new_message) and execute(message) doesnt compile. It gives Error:(38, 21) java: cannot find symbol.

**Comment by MonsterDeveloper** [comment]
Can you show full error code?

**Comment by maxkwaaste** [comment]
sure! thanks for your swift response.
Error:(62, 17) java: cannot find symbol
  symbol:   method execute(org.telegram.telegrambots.api.methods.send.SendMessage)
  location: class bestellen

**Comment by maxkwaaste** [comment]
class "bestellen" is class "bot" in your example
