### ISSUE TITLE
Question about Crawlers

### ISSUE THREAD

**Issue by poriniki** [MonsterDeveloper/java-telegram-bot-tutorial#5]
Hi. sorry I ask my question in here. I emailed you to "andrew@orlov.ink" but it seems your server is not working.
I want to know if we could write a crawler using telegram bots. And also could we join our bot to a public channel without any permission from the administrators like other real users in the telegram? (is invite link useable in this ?)

Thanks. Regards.

**Comment by MonsterDeveloper** [comment]
Hi! Sorry for such a long reply=D By saying 

> crawler using telegram bots

you mean you want to crawl a webpage when user sends you a page URL, don't you? If that's your case I recommend you to use [Crawler4J](https://github.com/yasserg/crawler4j) library.
