### ISSUE TITLE
if the internet connection is lost

### ISSUE THREAD

**Issue by bnja009** [MonsterDeveloper/java-telegram-bot-tutorial#6]
Hello, good afternoon, a question.
How is it done to cancel the sending of a message since it takes me a long time to send it, or how do I get it if the internet connection is lost, retrieve the message and send it back?

**Comment by MonsterDeveloper** [comment]
Hi! As far as I am concerned, it is impossible to cancel the message sending.

If you want to retry sending the messages, you can write a simple wrapper around `send` command, in which you call the same function (recursively).
